### PR TITLE
trakt.tv scrobbling

### PR DESCRIPTION
**Pull request by sttz**
This is an initial implementation of [trakt.tv](https://trakt.tv/) scrobbling for crunchyroll-html5. This is not intended to be merged as-is and instead this PR is intended to gather early feedback.

The UI is provisional and intended to be integrated with other settings and status UIs once they are implemented.

Since the Crunchyroll tracker serves similar functionality to the trakt.tv scrobbler, I wanted to keep the two in line. I first considered adding an `ITracker` interface but since this ended up very generic, I turned it into a general plugin interface instead.

One thing that wasn't clear to me from the codebase is how configuration should be handled. The trakt.tv API needs an client id and secret, and for testing it makes sense to be able to easily switch out settings that use trakt's staging server. I ended up putting the configuration in `inversify.config.ts` but there's probably a better place?

I first tried to use an existing library but the active JavaScript ones ([trakt.tv](https://github.com/vankasteelj/trakt.tv) and [traktapi2](https://github.com/PatrickE94/traktapi2)) are both made for Node and I had trouble getting them to work properly. There's a web-fork of the first called [nodeless-trakt](https://github.com/kdemoya/nodeless-trakt) which did work but is outdated and I wasn't sure if there was a chance for some required fixes to get merged. In the end I reimplemented the required functionality based on `trakt.tv`.

Getting trakt to find the episode to scrobble is a bit problematic. The series title in `IMediaMetadata` is the season title (or even a custom arc title for some long running series) and trakt only accepts the regular show title. trakt also wants to get the season number, which is not provided by `IMediaMetadata`. In the end, I resorted to parsing the HTML series information displayed below the video, which contains the show title and season / episode numbers. This means that scrobbling would be limited with the affiliate player and the scrobbling isn't currently activated in this case.

Some series are still not found by trakt and I'm unsure why, since the show title, season and episode perfectly match trakt's data. I requested access to their Google+ support group and will do some more testing.

#### How to use
A new «Connect with Trakt» button shows up at the bottom of the page (next to the other social media buttons). Click it an authorize crunchyroll-html5 to access your account. After being redirected back to Crunchyroll, the button should update to read «Disconnect from Trakt». Once connected, all videos played are scrobbled. A status UI will be displayed in the top right of the player chrome overlay.

### CODE REVIEW

**Comment by YePpHa** [comment]
First and foremost very nice work 👍. I have been looking at this a bit and I will definitely look at this a bit more in depth later. However, I do have a few thoughts and a bit of feedback from what I've looked at.

The configuration haven't really been implemented as I haven't been needing it yet. However, I can definitely see the need of it in this PR. I'm not 100% sure that `inversify.config.ts` is the correct place to place them. The `inversify.config.ts` is where you register the implementations and factories. Making two files named `config.staging.ts` and `config.prod.ts` might be better and then import one of them into `inversify.config.ts` depending on the compilation mode (production/staging) to bind them to `ITraktOptions`. Implementing this can be done by using [DefinePlugin](https://webpack.js.org/plugins/define-plugin/). I am also considering if the configuration change should be moved into its own PR.

As for finding the episode is a bit more problematic. I double checked what I receive from the Crunchyroll API (see [here](https://gist.github.com/YePpHa/4acf2695581812717fbff38be2482bd7)) and I'm only receiving the name of the season (in some cases the same as the name of the series). It seems like we're forced to parse the video page for the series name. This will require us to request the page for embedded videos and when going to the next video while in fullscreen. However, this can be done in the background while the player is playing as the player is not dependent on this information. An API should probably be made to retrieve this information and it might be best to do that at https://github.com/YePpHa/crunchyroll-lib.

__Feedback__
* I noticed that Trakt is using OAuth 2.0 (or some extension of it). I will suggest moving that part into its own generic class so that it can be used for future tracker implementations or just some arbitrary plugin. There is most likely also an OAuth 2.0 library that can be used.
* The plugin file is quite large and have multiple purposes. It could be split into multiple files. However, moving the OAuth functionality out might be enough (see [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design))).
* Love the plugin system (that's it).

**Comment by YePpHa** [comment]
Concerning the show `GeGeGe no Kitaro` I noticed something very interesting. In the title on the front page of Crunchyroll, `GeGeGe no Kitaro` is displayed as `GeGeGe no Kitaro (2018)`. I also noticed that `GeGeGe no Kitaro (2018)` is also under tags but with lower case. I'm not sure that this is a trend on Crunchyroll but might be a possible solution.

image

**Comment by YePpHa** [comment]
If the above solution is not enough, is it then possible to get all the shows i.e. with the name `GeGeGe no Kitaro` and then filter them by checking if the episode titles match? I can see that the old `GeGeGe no Kitaro (1968)` and the new `GeGeGe no Kitaro (2018)` have different episode titles.

**Comment by sttz** [comment]
I noticed the tag but wasn't aware the homepage was showing a different title. Gegege is the only show I'm aware of that has a tag like that (maybe it's a special tag that overrides the title in listings?).

Thanks for the idea to use the episode title to help matching where there are multiple possibilities!

In case of «LUPIN THE 3rd PART 5» the problem is that trakt doesn't return any results for that title and I don't see a general way to reliably transform titles. But maybe we have to add those titles as alternative names to TMDB, which I think tarkt imports as aliases. Not sure if they have a policy regarding adding season names as alternative names, though.

**Comment by sttz** [comment]
Hey, I just pushed some updates to the scrobbler. There are now more fallbacks in case the automatic match fails and more shows now scrobble correctly. There's some need to make sure TMDB's (and in turn trakt's) data is ok, adding alias titles and requesting to merge duplicate seasons.

I've now also split a "Scrobble" into its own class. This separates the whole lookup and fallback logic and allows for multiple scrobbles to exist in parallel, i.e. when playing the next video in fullscreen, where the previous one might still have a request pending and the new one already starts its lookup.

The plugin has grown in complexity and I was thinking about adding tests for the lookup logic. This would be easier if the scrobbler is a separate project and so I thought about the plugin system. One solution would be to load plugins from an external URL, store them in IndexedDB and loading them dynamically. This would also make the main extension smaller and allow to update the plugins independently. Does that sound like something worth pursuing or would you prefer just having all plugins in the main extension?

**Comment by sttz** [comment]
Hey, sorry for the long silence!

My Crunchyroll account got corrupted and I could no longer log in. It took a couple of months to sort it out with the customer support. 😰

When I got the service back, I also got the new official HTML5 player and didn't want to jinx my account by installing crunchyroll-html5.

So I decided to move the Trakt scrobbling to a separate project, which now lives here: https://github.com/sttz/TraktRoller

Therefore, I'm closing this pull request. The new scrobbling plugin probably doesn't work with crunchyroll-html5 but if someone needs that, feel free to open an issue or pull request.

**Comment by YePpHa** [comment]
Nice awesome work !!!

**Pull request closed without merging**
